name: NoFword
main: com.xuchaoji.craft.nofword.NoFWord
version: 2.0
commands:
    nfw:
        description: command for noFWord
        usage: /nfw
    nfw PASSWORD banword1 banword2 ...:
        description: add banwords, no permission needed, PASSWORD is in config file
        usage: /nfw PASSWORD banword1 banword2 ...